server:
  port: 8082


spring:
  data:
    mongodb:
      uri: mongodb+srv://parth12:Parth123@cluster0.dcla9uv.mongodb.net/cartdb?retryWrites=true&w=majority&appName=Cluster0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
